### ISSUE TITLE
No more utf-8 encoding in xml tag

### ISSUE THREAD

**Issue by jonathanasquier** [michaelkourlas/node-js2xmlparser#57]
Hi,
I'm quite sad I can't get `<?xml version='1.0' encoding='UTF-8'?>` instead of `<?xml version='1.0'?>` with the latest npm version

Is there a way?

Thanks!

**Comment by michaelkourlas** [comment]
There definitely is -- you have to pass a particular option to the parse function. Check the docs for details.

On Jun 28, 2017 7:43 AM, Jonathan Asquier <notifications@github.com> wrote:

Hi,
I'm quite sad I can't get <?xml version='1.0' encoding='UTF-8'?> instead of <?xml version='1.0'?> with the latest npm version

Is there a way?

Thanks!

**Comment by jonathanasquier** [comment]
Found it in the examples! awesome thanks! :)
